<a href="https://colab.research.google.com/github/vedika1090/My_portfolio_site/blob/main/tensorbaics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [2]:
my_list=[[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3,4)#created numpy array
np1


array([[0.46757398, 0.89585741, 0.28387645, 0.49175229],
       [0.07602398, 0.42708427, 0.16970382, 0.61676096],
       [0.27833208, 0.35391878, 0.52427634, 0.09488458]])

In [6]:
np1.dtype

dtype('float64')

In [7]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 0.9693, -0.8026,  0.3374, -0.8755],
        [ 0.8672, -2.4548, -0.2093, -0.5506],
        [ 0.6413,  0.4780, -0.1398, -0.3131]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
#create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4676, 0.8959, 0.2839, 0.4918],
        [0.0760, 0.4271, 0.1697, 0.6168],
        [0.2783, 0.3539, 0.5243, 0.0949]], dtype=torch.float64)

In [11]:
tensor_3d.dtype

torch.float32